site_name: SmartHomeDIY Documentation
site_description: SmartHomeDIY Documentation for Users and Developers
site_author: Benchuknii.
site_url: https://tbd.github.io/tbd/

# Repository
repo_name: benchuk/SmartHomeDIY
repo_url: https://github.com/benchuk/SmartHomeDIY
edit_uri: ""


# Copyright
copyright: 'Copyright &copy; Benchuknii MIT'

# Configuration
docs_dir: src
site_dir: docs
theme:
    name: material
    palette: 
        primary: 'blue'
        accent: 'light-blue'
    logo: style/benchuk.jpeg
    favicon: style/benchuk.jpeg


nav:
- Welcome: 'index.md'
- Users: Users.md
- Developers: Developers.md

    # Customization
extra:
  social:
    - type: globe
      link: https://www.2bitornot2bit.com/
    - type: facebook
      link: https://www.facebook.com/2bitornot2bit/
    - type: instagram
      link: https://www.instagram.com/2bitornot2bit/
    - type: twitter
      link: https://twitter.com/benchuknii
    - type: github-alt
      link: https://github.com/benchuk/SmartHomeDIY
    - type: linkedin
      link: https://www.linkedin.com/in/ben-amsallem-9bb0ab141/
    - type: youtube
      link: https://www.youtube.com/channel/UCEKhV04E8bD_pZz_lFGwjqQ?view_as=subscriber
      